apiVersion: v1
kind: Secret
metadata:
  name: pleasanter-db-secret
  namespace: pleasanter
type: Opaque
data:
  POSTGRES_USER: cGxlYXNhbnRlcg==
  POSTGRES_PASSWORD: cGxlYXNhbnRlcl9wdw==
  POSTGRES_DB: cGxlYXNhbnRlcl9kYg==
stringData:
  CONNECTION_STRING: "Server=postgres;Database=pleasanter_db;UID=${POSTGRES_USER};PWD=${POSTGRES_PASSWORD}"
  OWNER_CONNECTION_STRING: "Server=postgres;Database=#ServiceName#;UID=#ServiceName#_Owner;PWD=Pleasanter_Owner_Password"
  USER_CONNECTION_STRING: "Server=postgres;Database=#ServiceName#;UID=#ServiceName#_User;PWD=pleasanter"
  ConnectionStrings__DefaultConnection: "Server=postgres;Database=pleasanter_db;UID=${POSTGRES_USER};PWD=${POSTGRES_PASSWORD}"
  ConnectionStrings__Key: "Server=postgres;Database=pleasanter_db;UID=${POSTGRES_USER};PWD=${POSTGRES_PASSWORD}"
  Implem.Pleasanter_Rds_PostgreSQL_SaConnectionString: "Server=postgres;Database=${POSTGRES_DB};UID=${POSTGRES_USER};PWD=${POSTGRES_PASSWORD}"
  Implem.Pleasanter_Rds_PostgreSQL_OwnerConnectionString: "Server=postgres;Database=#ServiceName#;UID=#ServiceName#_Owner;PWD=Pleasanter_Owner_Password"
  Implem.Pleasanter_Rds_PostgreSQL_UserConnectionString: "Server=postgres;Database=#ServiceName#;UID=#ServiceName#_User;PWD=${POSTGRES_PASSWORD}"